name: Test Action
on:
    push:
      branches:
        - main
        - master
jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - name : Check out Repository
          uses: actions/checkout@v3

        - name: set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'adopt'
            cache: gradle

        - name: Grant execute permission for gradlew
          run: chmod +x gradlew

        - name: Build with Gradle
          run: ./gradlew build

        - name: Set Docker Buildx Environment
          id: buildx
          run: |
            docker buildx create --use
            echo "::set-output name=buildx::$(docker buildx inspect --bootstrap | tr -d '\r\n')"

        - name: Build Docker Image
          run: docker build -t njk7740/test:latest .