name: Test Action
on:
    push:
      branches:
        - main
        - master
jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - name : Check out Repository
          uses: actions/checkout@v3
        - name: set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'adopt'
            cache: gradle
        - name: Grant executegi permission for gradlew
          run: chmod +x gradlew
        - name: Build with Gradle
          run: ./gradlew test