name: Test Action
on:
    push:
      branches:
        - main
        - master
jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - name : Check out Repository
          uses: actions/checkout@v3

        - name: set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'adopt'
            cache: gradle

        - name: Grant execute permission for gradlew
          run: chmod +x gradlew

        - name: Build with Gradle
          run: ./gradlew build

        - name: Run Spring Boot Application
          run: java -jar build/libs/basic1-0.0.1-SNAPSHOT.jar

        - name: Build Docker Image
          uses: docker/build-push-action@v2
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: njk7740/test:latest